### ISSUE TITLE
Some of the skills have long name .... 

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/gm-magic#12]
Example: 
![skill](https://cloud.githubusercontent.com/assets/8476884/10850849/ac1f2340-7f1f-11e5-906f-ca838ffda0e5.png)
We need to change the way we collect skills at the moment.

**Comment by nelsonic** [comment]
@heron2014 can you paste a link to an example profile which has skills with *long names*...?

**Comment by SimonLab** [comment]
@nelsonic [iteles profile](https://www.linkedin.com/in/iteles) has some skills with long names

**Comment by SimonLab** [comment]
One solution: Instead of selecting the text of the skill, we are now selecting the href of the link and with a regular expression targeting only the name of the skill inside the url
![skill](https://cloud.githubusercontent.com/assets/6057298/10904707/25c60f2a-820d-11e5-86cb-dd99331e8ed8.png)
see [L55](https://github.com/FAC-GM/gm-magic/blob/8fc93f18b4758ff83e058f65f5d2caeebe9285b0/js/scrape.js#L55)

**Comment by nelsonic** [comment]
@SimonLab will selecting the href attribute and extracting the string between the final forward slash and question mark work as a *general* rule?

**Comment by SimonLab** [comment]
It looks like selecting the text after the last slash and before the query string is indeed a general rule but I will need to write some tests to be sure.
I also check that if the skill is not defined on LinkedIn there is still a link and a href attribute with the name.

**Comment by SimonLab** [comment]
This issue has been resolved by selecting the name in the a tag
