### ISSUE TITLE
How to use npm packages on the extension?

### ISSUE THREAD

**Issue by SimonLab** [FAC-GM/gm-magic#8]
There are a few usefull packages on npm (cheerio, public-profile-parser,...) and I'd like to reuse them. However a chrome extension is composed with a set of front-end scripts.
So: 
- Is it possible to use npm packages with a chrome extension?
- If yes, what is the best way to do it?

**Comment by SimonLab** [comment]
[Browserify](https://github.com/substack/node-browserify) looks to be one solution!

**Comment by nelsonic** [comment]
@SimonLab what NPM module *exactly* do you need to run in the browser?

**Comment by SimonLab** [comment]
@nelsonic I'd like to use [cheerio](https://www.npmjs.com/package/cheerio), linkedin-public-profile-parser and a new package (linkedin-private-profile-parser, we need to create this one) to extract the information from the DOM. The idea is instead of using javascript (or jquery) on the [content script](https://developer.chrome.com/extensions/content_scripts) to select our data, we pass the DOM to a background page where we can reuse some packages and do the heavy work.
I think it's one way to do it, do you think of another one?

**Comment by nelsonic** [comment]
Please don't export Cheerio for the browser ... 
Cheerio is ***JQuery*** for the *server* ... https://github.com/cheeriojs/cheerio
i.e. if you need JQuery selectors in the browser, *just* use JQuery.

But before you dive in, *please* read "You might not need jQuery": http://youmightnotneedjquery.com/

The Chrome Extension can (*should*) be written without any frameworks or libraries.
We can *use* the *knowledge* and *techniques* from the `public-profile-parser` to the browser parser, but we are certainly not going to Browserify server code. 
People who employ Browserify/Babel/etc to re-use their code have *given up* on writing *high performance* code. 

The only reason I used `cheerio` for the parser was to simplify the code (*on the server*).
On the client things can & should be written *smaller* because the browser's DOM is *much slower*.

**Comment by heron2014** [comment]
@nelsonic  and @SimonLab I would love to use vanilla Javascript just for even learning purpose even though it might be longer process.

**Comment by nelsonic** [comment]
The reason we encourage people *not* to use JQuery at FAC is that *you don't need it*!
The *reason* we use Cheerio on the server is to simplify DOM parsing on a platform where there is no native DOM API ... When I've written web parsers in the past I've used "*raw*" XPath: https://developer.mozilla.org/en-US/docs/Web/XPath its *ugly* and has a *steep learning curve*.

There's no *reason* "*Vanilla JS*" should take longer. 
Use standard DOM selectors to extract the data and XHR to send it.
see: https://github.com/nelsonic/web-form-to-google-sheet/blob/e14bdd753b8d4c01148073d64a8ae9a522216598/_lon.html#L356

**Comment by SimonLab** [comment]
ok thanks, I didn't have look yet at the performance of a Browserified package and thought it was ok to do it. So to recap we need to trassfer the logic of some packages into the chrome extension js files

**Comment by nelsonic** [comment]
To recap:
+ Build an extension. 
+ Extract skills from page using standard DOM selectors.

Use the work we did on the  `public-profile-parser` as a *guide*.
But write *new* methods for the *new* environment/platform.

**Comment by SimonLab** [comment]
:+1:
